name: release

on:
  pull_request:
    types: [labeled]
    branches:
      - master

jobs:
  prepare-release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSHER_CI_GITHUB_PRIVATE_TOKEN }}
          fetch-depth: 0
      - name: Get current version
        shell: bash
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          repository: pusher/actions
          token: ${{ secrets.PUSHER_CI_GITHUB_PRIVATE_TOKEN }}
          path: .github/actions
      - uses: ./.github/actions/prepare-version-bump
        id: bump
        with:
          current_version: ${{ env.CURRENT_VERSION }}
          token: ${{ secrets.PUSHER_CI_GITHUB_PRIVATE_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - name: Commit and push version bump
        shell: bash
        run: |
          echo "$(jq '.version = "${{ steps.bump.outputs.new_version }}"' package.json)" > package.json

          git add package.json CHANGELOG.md
          git commit -m "Bump to version ${{ steps.bump.outputs.new_version }}"
          git push
